"""
SQLite persistence scaffold.

Lifted in idiom from o27v2's `db.py`: a single connection helper, an
idempotent `init_db()` that creates the schema, and writes wrapped in a
transaction. This is the skeleton schema (players, matches, match_stats) —
leagues / seasons / ratings / circuits / recruiting land on top in later
phases (see docs/DESIGN-college-tennis-sim-fork.md §6).

DB path: $TENNIS_DB_PATH or ./tennis.db
"""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager

from engine.match import MatchResult
from .dbpath import resolve_db_path

DB_PATH = resolve_db_path()   # volume path if writable, else a local fallback

SCHEMA = """
CREATE TABLE IF NOT EXISTS players (
    id          INTEGER PRIMARY KEY,
    pid         TEXT UNIQUE,     -- stable prospect id (generators), for round-trip
    name        TEXT NOT NULL,
    country     TEXT,
    gender      TEXT,
    serve_power REAL, serve_placement REAL, return_game REAL,
    forehand REAL, backhand REAL, movement REAL,
    stamina REAL, mental REAL, consistency REAL,
    rating      REAL,           -- modified-UTR (filled by rating pass, P5)
    reliability REAL,
    -- Origin / identity flavor (generated by app.development.generate_prospect;
    -- persisted so it survives a write-back instead of being regenerated). The
    -- schema dropped these originally, so any roster written to disk lost its
    -- hometowns / majors / scholarships — this is that gap closed.
    school          TEXT,
    division        TEXT,
    class_year      TEXT,
    hometown        TEXT,
    high_school     TEXT,
    birthday        TEXT,
    major           TEXT,
    secondary_country TEXT,
    region          TEXT,
    academic_rating INTEGER,
    recruit_stars   INTEGER,
    scholarship     REAL,        -- equivalency fraction (app.economy)
    walk_on         INTEGER      -- 0/1 roster filler
);

CREATE TABLE IF NOT EXISTS matches (
    id          INTEGER PRIMARY KEY,
    seed        INTEGER NOT NULL,
    fidelity    TEXT NOT NULL,
    fmt         TEXT,           -- JSON of MatchFormat
    p0_id       INTEGER, p1_id INTEGER,
    winner      INTEGER,
    scoreline   TEXT,
    games_p0    INTEGER, games_p1 INTEGER
);

CREATE TABLE IF NOT EXISTS match_stats (
    match_id    INTEGER NOT NULL,
    side        INTEGER NOT NULL,   -- 0 or 1
    aces INTEGER, double_faults INTEGER,
    first_serve_pct REAL, serve_points_won_pct REAL,
    break_points_faced INTEGER, break_points_saved INTEGER,
    break_points_converted INTEGER,
    winners INTEGER, unforced_errors INTEGER, points_won INTEGER,
    PRIMARY KEY (match_id, side)
);
"""


def connect(path: str | None = None) -> sqlite3.Connection:
    conn = sqlite3.connect(path or DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


# Columns the migration backfills onto a pre-existing `players` table that was
# created before origins/scholarships were persisted. Mirror SCHEMA above.
_PLAYER_MIGRATIONS: tuple[tuple[str, str], ...] = (
    ("pid", "TEXT"), ("school", "TEXT"), ("division", "TEXT"),
    ("class_year", "TEXT"), ("hometown", "TEXT"), ("high_school", "TEXT"),
    ("birthday", "TEXT"), ("major", "TEXT"), ("secondary_country", "TEXT"),
    ("region", "TEXT"), ("academic_rating", "INTEGER"),
    ("recruit_stars", "INTEGER"), ("scholarship", "REAL"), ("walk_on", "INTEGER"),
)


def _migrate_players(conn: sqlite3.Connection) -> None:
    """Add any origin/scholarship columns missing from an older players table.
    SQLite has no `ADD COLUMN IF NOT EXISTS`, so we diff against PRAGMA."""
    have = {r["name"] for r in conn.execute("PRAGMA table_info(players)")}
    for col, decl in _PLAYER_MIGRATIONS:
        if col not in have:
            conn.execute(f"ALTER TABLE players ADD COLUMN {col} {decl}")


def init_db(path: str | None = None) -> None:
    with connect(path) as conn:
        conn.executescript(SCHEMA)
        _migrate_players(conn)
        conn.commit()


def bootstrap() -> None:
    """Create every module's schema once, eagerly, at process start.

    All these modules share one SQLite file. If a table is created lazily for
    the first time *inside* another module's open write transaction (e.g.
    overrides during world seeding), the two writers deadlock → 'database is
    locked'. Creating all schemas up front, before any long transaction, makes
    every later connection a clean read/write under WAL. Safe to call repeatedly.
    """
    init_db()
    from app import overrides, seasonmode, world, honors
    overrides.init_schema()
    seasonmode.init_schema()
    world.init_schema()
    honors.init_schema()


# ---------------------------------------------------------------------------
# Prospect persistence — write a generated roster to disk, origins and all.
# ---------------------------------------------------------------------------

# (attribute name on the engine driver -> players column) for the 9 skills.
_SKILL_COLS = (
    "serve_power", "serve_placement", "return_game", "forehand", "backhand",
    "movement", "stamina", "mental", "consistency",
)


def save_prospect(conn: sqlite3.Connection, pr, *, school: str = "",
                  division: str = "") -> int:
    """Upsert one app.development.Prospect (keyed on its stable `pid`),
    persisting attributes AND the full origin/scholarship payload. Returns the
    row id."""
    drivers = pr.engine_player()
    skills = {c: float(getattr(drivers, c, 0.0) or 0.0) for c in _SKILL_COLS}
    cols = (
        "pid", "name", "country", "gender", *_SKILL_COLS,
        "rating", "reliability", "school", "division", "class_year",
        "hometown", "high_school", "birthday", "major", "secondary_country",
        "region", "academic_rating", "recruit_stars", "scholarship", "walk_on",
    )
    vals = (
        pr.pid, pr.name, pr.country, pr.gender,
        *(skills[c] for c in _SKILL_COLS),
        float(getattr(pr, "rating", 0.0) or pr.str_value()),
        float(getattr(pr, "reliability", 0.0) or 0.0),
        school or "", division or "", getattr(pr, "class_year", ""),
        getattr(pr, "hometown", ""), getattr(pr, "high_school", ""),
        getattr(pr, "birthday", ""), getattr(pr, "major", ""),
        getattr(pr, "secondary_country", ""), getattr(pr, "region", ""),
        int(getattr(pr, "academic_rating", 0) or 0),
        int(getattr(pr, "recruit_stars", 0) or 0),
        float(getattr(pr, "scholarship", 0.0) or 0.0),
        1 if getattr(pr, "walk_on", False) else 0,
    )
    placeholders = ",".join("?" * len(cols))
    updates = ",".join(f"{c}=excluded.{c}" for c in cols if c != "pid")
    cur = conn.execute(
        f"INSERT INTO players ({','.join(cols)}) VALUES ({placeholders}) "
        f"ON CONFLICT(pid) DO UPDATE SET {updates}",
        vals,
    )
    return cur.lastrowid


def load_player_row(conn: sqlite3.Connection, pid: str) -> dict | None:
    """Read a persisted player back as a plain dict (origins included)."""
    row = conn.execute("SELECT * FROM players WHERE pid = ?", (pid,)).fetchone()
    return dict(row) if row else None


@contextmanager
def transaction(path: str | None = None):
    conn = connect(path)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def save_match(conn: sqlite3.Connection, result: MatchResult, *, seed: int,
               fmt_json: str = "", p0_id: int | None = None,
               p1_id: int | None = None) -> int:
    cur = conn.execute(
        "INSERT INTO matches (seed, fidelity, fmt, p0_id, p1_id, winner, "
        "scoreline, games_p0, games_p1) VALUES (?,?,?,?,?,?,?,?,?)",
        (seed, result.fidelity, fmt_json, p0_id, p1_id, result.winner,
         result.scoreline, result.games_won[0], result.games_won[1]),
    )
    match_id = cur.lastrowid
    if result.fidelity != "fast":
        for side, s in enumerate(result.stats):
            conn.execute(
                "INSERT INTO match_stats (match_id, side, aces, double_faults, "
                "first_serve_pct, serve_points_won_pct, break_points_faced, "
                "break_points_saved, break_points_converted, winners, "
                "unforced_errors, points_won) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                (match_id, side, s.aces, s.double_faults, s.first_serve_pct,
                 s.serve_points_won_pct, s.break_points_faced, s.break_points_saved,
                 s.break_points_converted, s.winners, s.unforced_errors, s.points_won),
            )
    return match_id
