"""Categorized index of docs/AAR-*.md, grouped by game system, for the
in-app Game Guide (Tools > Guide, /guide) appendix. Generated once from
the AAR titles; update by hand when AARs are added/renamed rather than
re-deriving at request time (avoids a filesystem scan on every page load,
and keeps category assignment a deliberate editorial choice, not a guess).
"""

APPENDIX_CATEGORIES = [
    {"name": 'Divisions, Conferences & Realignment', "items": [
        ('AAR-conference-division-restructure.md', 'Conference / division restructure, single-sex fix, HBCU Legacy League'),
        ('AAR-cross-division-scheduling-NOT-DONE.md', 'Cross-division non-conference scheduling (NOT DONE — deferred)'),
        ('AAR-d3-d4-play-play-format.md', 'Division III/IV "play-play": D3/D4 finish every match'),
        ('AAR-d4-academic-realignment.md', 'D4 academic realignment: lifting stranded elite LACs above D3'),
        ('AAR-d4-cross-division-guard.md', 'Cross-division scheduling: geography- and prestige-gated reach'),
        ('AAR-division-4-academic-tier.md', 'NCAA Division IV: an academic-first tier carved out of D3'),
        ('AAR-division-dual-formats.md', 'per-division dual formats: the expanded singles cards'),
        ('AAR-independent-doubles-lineup.md', 'Independent doubles lineup (coach-set pairings)'),
        ('AAR-meridian-academic-realignment.md', 'Meridian "nerdy major" build + academic-school realignment (round 2)'),
        ('AAR-postseason-best-six-lineups.md', 'Postseason lineups: strict best six (no resting in elimination play)'),
        ('AAR-realignment-acc-bigten-sec-round.md', 'Realignment round: ACC/Big Ten/SEC reshuffle, UAA & Yankee rebuild, three promotions'),
        ('AAR-realignment-bracket-utr-calibration.md', 'Conference realignment, a 96-team D1 bracket, and a UTR-true talent scale'),
        ('AAR-realistic-schedules-and-realignment.md', 'Realistic 25-dual schedules (+ the conference realignment behind them)'),
        ('AAR-recruit-territory-israel-canada.md', 'D3 trim, Sarah Lawrence academic move, per-school recruiting territories'),
        ('AAR-western-sky-seas-conference-split.md', 'Late conference swap: Western Sky / Western Seas splits + SLIAC / USA South moves'),
    ]},
    {"name": 'Recruiting & Scholarship Economy', "items": [
        ('AAR-base-roster-nationality-by-level.md', 'Base-roster nationality by program level (international share + regional bias)'),
        ('AAR-coach-localism-recruiting.md', 'Coach-dictated recruiting: localism, nationality tilt & home-country pipeline'),
        ('AAR-conference-tier-economy.md', 'Conference-tier economy: re-leveled tiers, tier-keyed budgets, steep costs, D3/D4 gems'),
        ('AAR-diii-d4-economy-and-recruit-realism.md', 'DIII/D4 economy overhaul + recruiting realism'),
        ('AAR-dynamic-prestige-momentum.md', 'Dynamic prestige (YoY momentum from over/under-performance)'),
        ('AAR-elite-signings-and-schedule-colors.md', 'elite junior signings, play-in de-confliction, conference strength, schedule colors'),
        ('AAR-fog-of-war-recruiting.md', 'Fog-of-war recruiting (the model it was always supposed to be)'),
        ('AAR-junior-rankings-doubles.md', 'Junior Ranking Points Ledger & Doubles'),
        ('AAR-name-pool-diversity.md', 'Name pool expansion + country diversity (diaspora names)'),
        ('AAR-nation-talent-rankings.md', 'National talent rankings (investment / grassroots)'),
        ('AAR-nationality-editor-live-percentages.md', 'Nationality editor: live percentages + the US "multiplier" no-op'),
        ('AAR-polls-regional-rankings-hometown-territory.md', 'Media/Coaches polls, regional rankings, hometown breadth, territory recruiting'),
        ('AAR-portal-polish-junior-season.md', 'Portal polish, badges, scholarships & the 36-week junior season'),
        ('AAR-recruit-rating-clarity.md', 'Recruit rating clarity: the board reads today, not the ceiling'),
        ('AAR-recruit-redesign-analytics-bureau.md', 'Recruit-page redesign + Analytics Bureau'),
        ('AAR-recruiting-board-commit-column.md', 'Recruiting board never showed signings'),
        ('AAR-recruiting-budget-economy.md', 'UTR-true talent + a recruiting budget economy'),
        ('AAR-recruiting-division-radar.md', 'Division radar recruiting: D1 never sees sub-level recruits; D3 signs all season'),
        ('AAR-recruiting-elite-signing-and-division-filter.md', "Elite recruits weren't signing + signing tracker showed every division"),
        ('AAR-recruiting-fill-transfer-portal.md', 'Recruiting fill (prestige-aspirational), transfer portal, flip trail'),
        ('AAR-recruiting-interest-and-commitment-timing.md', 'Recruiting realism: interest diversity + commitment timing'),
        ('AAR-recruiting-juniors-portal.md', 'Recruiting & Juniors Data Portal'),
        ('AAR-recruiting-prestige-budget-redesign.md', 'recruiting prestige & budget redesign (incl. academic D3)'),
        ('AAR-recruiting-realism-and-bureau.md', 'Recruiting realism (prestige tiers, star gates) + Bureau usability'),
        ('AAR-recruiting-signing-pace.md', 'Recruiting signing pace (drip across the season, skewed by rank)'),
        ('AAR-region-mix-editor-weights.md', 'Region-mix editor: direct weights (replacing capped multipliers)'),
        ('AAR-scholarship-economy-and-program-cities.md', 'Scholarship economy, program cities & persisted player origins'),
        ('AAR-scholarship-full-funding-rule.md', 'Scholarship caps: I reverted a rule change, then corrected course'),
        ('AAR-us-state-allocation-guam.md', 'Organized US-state recruit allocation + Guam as a US territory'),
        ('AAR-world-model-flags-recruiting.md', 'International world model, flags & the recruiting board'),
    ]},
    {"name": 'Rosters, Talent & the Player Model', "items": [
        ('AAR-player-coach-model-foundation.md', 'Player and Coach Model Foundation'),
        ('AAR-power6.md', 'Power 6 (roster strength)'),
        ('AAR-roster-display-and-conf-abbrev.md', 'full roster in My Program lineup + conference-name abbreviation'),
        ('AAR-roster-expansion-walkons-recruit-pool.md', 'Roster expansion, walk-on sourcing, and a recruit pool sized to demand'),
        ('AAR-roster-floor-and-walkon-personas.md', 'a program with fewer than six players crashed the engine'),
        ('AAR-service-academy-us-only-rosters.md', 'Service academies roster US citizens ONLY'),
        ('AAR-str-one-results-stat-ovr-cards-only.md', 'One STR (results-based stat); OVR/attributes are card-only evaluation'),
        ('AAR-str-semantics-results-only-overall-static.md', 'STR is results-only; OVERALL is the static talent number (two-STR defect)'),
        ('AAR-talent-compression.md', 'Talent compression + the pro tier'),
        ('AAR-team-class-ranking-score.md', 'Team class rankings: rank × STR × star-value scoring'),
        ('AAR-tenniseye-results-star-rating.md', 'TennisEye: a results-based second star rating'),
    ]},
    {"name": 'The Transfer Portal', "items": [
        ('AAR-fall-transfer-portal.md', 'Fall transfer portal (post-ITA talent reshuffle)'),
        ('AAR-my-transfer-targets.md', 'My Transfer Targets (Fit Finder, inverted) + team-picker by conference'),
        ('AAR-portal-batch-edit-paging.md', 'Portal batch editing + settable page size / slate search'),
        ('AAR-portal-rankings.md', 'Portal Rankings (transfer-class board, On3/247 style)'),
        ('AAR-portal-search.md', 'Portal Search (searchable placeable pool by hometown / region / class)'),
        ('AAR-preseason-portal-all-division-scan.md', 'Pre-season portal: scan ALL divisions, and the design intent behind it'),
        ('AAR-preseason-portal-lineup-tables-nit-rename.md', 'Pre-season portal, Lineup Lab table rebuild, ITA → Preseason NIT rename'),
        ('AAR-transfer-realism.md', 'Transfer realism (division-respecting, one per career)'),
    ]},
    {"name": 'Rankings & the Power Index', "items": [
        ('AAR-toss-per-division-flight-weights.md', 'the Power Index had no weights for two thirds of a D1 lineup'),
    ]},
    {"name": 'Injuries', "items": [
        ('AAR-injuries.md', 'Injuries: dice rolls on talent + a lever that forces depth'),
    ]},
    {"name": 'Championships, Cups & Brackets', "items": [
        ('AAR-bracket-projection-seeding-and-juniors-split.md', 'Bracket projection seeds AFTER selection; juniors National/International split'),
        ('AAR-committee-seed-reveal-and-zero-point-fixes.md', 'Committee seed score: reveal/sim seeding drift + zero-point résumé spread'),
        ('AAR-committee-seed-score-and-conference-tiers.md', 'Committee Seed Score + prestige-percentile conference tiers'),
        ('AAR-davis-bjk-cups.md', 'Davis Cup / Billie Jean King Cup (national-team cups, V1)'),
        ('AAR-doubles-engine-and-championship.md', 'Doubles Engine, NCAA Individual Championships & Tennis Seeding'),
        ('AAR-individual-champions-past-winners.md', 'Past winners of the NCAA singles & doubles championships'),
        ('AAR-individual-championship-uncached-recompute.md', 'NCAA individual championships recomputed on every request (dead cache)'),
        ('AAR-ita-kickoff-indoor-opener.md', 'ITA Kickoff Weekend + National Team Indoor (season opener)'),
        ('AAR-ita-rankings-and-seeding.md', 'ITA-style rankings (team, singles, doubles) + seeding'),
        ('AAR-ncaa-bracket-region-drift.md', "the NCAA bracket's regions drifted, and the page was never a bracket"),
        ('AAR-ncaa-bracketing.md', 'NCAA bracket: real bracketing constraints'),
        ('AAR-ncaa-region-seed-display.md', 'NCAA field shown by region seed (1–24 / 1–16), not overall 1–96'),
        ('AAR-ncaa-seed-power-conference-preference.md', 'power-conference preference in NCAA seeding'),
        ('AAR-postseason-and-archives.md', 'Postseason visibility, clarity & season archives'),
        ('AAR-postseason-record-and-performance-awards.md', 'Postseason record, bracket-seed persistence, performance-based awards'),
        ('AAR-postseason-visibility-and-bracket.md', 'Postseason visibility: results browser, real bracket, reveal phase'),
        ('AAR-preseason-nit-bracket.md', 'the Preseason NIT is now the same bracket as the NCAA tournament'),
        ('AAR-regional-bracket-scurve.md', 'Regional (S-curve) NCAA bracket structure'),
        ('AAR-true-seed-no-conference-separation.md', 'True seed: no conference separation in the NCAA bracket'),
    ]},
    {"name": 'Awards, Honors & the Hall of Fame', "items": [
        ('AAR-awards-name-quality.md', 'Awards-list name quality (gender pools, junk surnames, list length)'),
        ('AAR-awards-position-weighted-wins.md', 'Awards select on position-weighted wins (rating removed)'),
        ('AAR-awards-timing-and-dreamsheets.md', "Awards gated to season's end + dreamsheet realism"),
        ('AAR-career-honors-coaches.md', 'Career Honors, Coaches as Entities, Hall of Fame'),
        ('AAR-program-honors-season-history.md', 'Program Honors & Season Results on school pages'),
    ]},
    {"name": 'Coaches', "items": [
        ('AAR-coach-career-lineage-and-player-conversion.md', 'Coach career lineage and player-to-coach conversion'),
        ('AAR-coach-careers-and-moves.md', 'Coach careers, moves, and the assistant award'),
        ('AAR-coach-development-growth.md', 'Coach development score drives player growth (±30%)'),
        ('AAR-coach-move-cascade.md', 'Coach "Move to any program" as a Gender → Conference → School cascade'),
        ('AAR-coach-retire-and-editor-moves.md', 'Coach moves in the Editor + Retire'),
        ('AAR-staff-search.md', 'Staff Search (scout coaches by ability, spot HC-ready assistants)'),
    ]},
    {"name": 'Jefferson & the JHSAA', "items": [
        ('AAR-jefferson-state-integration.md', 'Jefferson: a fictional US state, its juniors and its colleges'),
        ('AAR-jhsaa-bracket-score-sides.md', 'the bracket showed the winner losing, and half of it was right'),
        ('AAR-jhsaa-district-schedule-passes.md', 'a correct double round robin that no high school has ever played'),
        ('AAR-jhsaa-high-school-season.md', 'The JHSAA: a simulated high-school season inside the college sim'),
        ('AAR-jhsaa-program-history-and-design-pass.md', 'the JHSAA becomes a world surface: program history, and the design pass'),
        ('AAR-jhsaa-talent-identity-and-toc.md', "what a program IS, and the tournament that proved it wasn't working"),
    ]},
    {"name": 'The Pro Tour (GTT)', "items": [
        ('AAR-gtt-add-drop-waiver-wire.md', 'GTT in-season add/drop waiver wire'),
        ('AAR-gtt-college-graduate-pipeline.md', 'GTT college graduate pipeline'),
        ('AAR-gtt-pro-tour-pipeline.md', 'Global Team Tennis: the Pro Tour & the College→Pro Pipeline'),
        ('AAR-gtt-world-clock.md', "GTT runs on the college world's clock (lockstep)"),
        ('AAR-pro-grad-transfers.md', 'Pros are grad transfers ("Gr"): one season, then gone'),
        ('AAR-pro-league-parity-injuries-and-development.md', 'building out the pro league: injuries, development, and club playing styles'),
        ('AAR-pro-tour-global-mix.md', '"Pro Tour" global nationality mix + international-share dial'),
    ]},
    {"name": 'Career Mode, Analytics Bureau & Editor Tools', "items": [
        ('AAR-analytics-bureau-stale-rosters.md', "Analytics Bureau linked to stale rosters; every player click 404'd"),
        ('AAR-career-coached-lineup.md', "Career mode: the coached team's lineup reaches the court"),
        ('AAR-career-history-search-bureau-links.md', 'Player career history, player search, Bureau profile links'),
        ('AAR-career-job-offers.md', 'Career mode: prestige-gated job offers (coaching carousel)'),
        ('AAR-career-nonconf-scheduling.md', 'Career mode: preseason non-conference scheduling'),
        ('AAR-career-record-boxes.md', 'Career record boxes (per-line W-L), singles + doubles'),
        ('AAR-editor-batch-move.md', 'Editor batch player moves (kill the one-by-one friction)'),
        ('AAR-lineup-architect-and-editor-card-fix.md', "Lineup Architect + editor's stale 6+3 card"),
        ('AAR-lineup-lab.md', "Lineup Lab (Analytics Bureau): every team's singles ladder by conference"),
        ('AAR-team-scanner.md', 'Team Scanner: cross-division team board, OVR-first'),
        ('AAR-underplaced-fit-diversity.md', 'Underplaced Talent "FITS" diversity (calibre-band by grade)'),
    ]},
    {"name": 'Match Engine, Simulation & Box Stats', "items": [
        ('AAR-box-stat-persistence.md', 'Box-stat persistence: real per-match stats without touching outcomes'),
        ('AAR-dual-concurrent-singles-box-score.md', 'Dual box score: team labels + concurrent singles with partial scores'),
        ('AAR-engine-box-stat-balance.md', 'Box-stat balance: winners, aces, double faults, UE variety'),
        ('AAR-engine-realism-playing-time-unification.md', 'Match Realism, Playing-Time Guarantee, Season-Mode Unification & Staged UI'),
        ('AAR-engine-seasons-recruiting-buildout.md', 'Engine, Seasons, Ratings, Recruiting & Web Build-out'),
        ('AAR-engine-upset-recalibration-and-rating-scale-map.md', 'Engine upset recalibration, realism eval harness & rating-scale map'),
        ('AAR-point-attribution-winner-error-mix.md', 'box scores said a player hit zero winners (and another hit 47)'),
        ('AAR-talent-engine-calibration.md', 'Match Engine & Talent/Ratings Calibration'),
    ]},
    {"name": 'World Engineering — Saves, Caches, Performance & Infra', "items": [
        ('AAR-boot-cache-warm.md', 'boot-time cache warm (stop the crash-on-reload loop)'),
        ('AAR-bureau-lineup-stale-after-fall-portal.md', 'Analytics Bureau & Lineup Lab stale after the fall portal (week-only cache stamp)'),
        ('AAR-cache-invalidation-scope-lineup-stall.md', 'a one-team lineup edit rebuilt the whole world (cache-invalidation SCOPE)'),
        ('AAR-coach-staff-cache-isolation.md', 'coach-staff cache stale across registry resets'),
        ('AAR-cold-prime-loader-health-503-loop.md', 'Instant loader + health that never blocks on a cold prime (the 503 loop)'),
        ('AAR-data-portal-sim-integration.md', 'Data portal export feed read a phantom preseason season'),
        ('AAR-editor-roster-overload.md', 'Editor built every roster just to list teams'),
        ('AAR-export-portal-health-check.md', 'Export-Portal Health-Check Timeout'),
        ('AAR-new-save-stale-cups-pros.md', "new save inherits the prior save's cups & pro leagues (stale players)"),
        ('AAR-offseason-visible-steps-cups-and-pros.md', 'the cups and the pro league ran invisibly inside the rollover'),
        ('AAR-one-world-binding.md', 'One world per save: the seed-matching failure (GTT + World Cups)'),
        ('AAR-oom-recruit-cadre-memory.md', 'Memory & Preseason segment: OOM fix, nationality bands, universe selection, preseason gate'),
        ('AAR-parallel-generation.md', 'Parallel world build + junior circuit (use the cores)'),
        ('AAR-perf-regression-and-power-index-thread-race.md', 'ranking-cache perf regression, the power_index thread-race outage, and the infra thrash'),
        ('AAR-single-gender-world-phase.md', "World phase stuck on 'regular' in single-gender saves"),
        ('AAR-str-cache-race-condition.md', 'Production 500: race condition KeyError in `season_player_str`'),
        ('AAR-takeover-hang-loader-salt-keying.md', 'Team-takeover hang: cold-prime loader must key on the league salt, not a process flag or rowid'),
        ('AAR-unified-world-session.md', 'Unified world, recruiting realism, lineups (PR #14)'),
        ('AAR-universe-desync-season-hub-advance.md', 'two advance buttons desynced the universes (women\'s rankings looked "wrong")'),
        ('AAR-world-aware-generation.md', 'World-Aware Generation & Unified Recruit Class'),
    ]},
    {"name": 'UI, Onboarding & Content', "items": [
        ('AAR-atp-wta-data-portal.md', 'ATP/WTA-style Data Portal'),
        ('AAR-cta-individual-rankings-census-regions.md', 'CTA individual rankings (national / regional / newcomer) + census-division regions'),
        ('AAR-logo-backfill.md', 'Real-logo sweep (every school gets a mark)'),
        ('AAR-mobile-responsive-recruiting-intl-share.md', 'Mobile responsiveness, recruiting consistency, tunable international share'),
        ('AAR-onboarding-ui-pagination-awards.md', 'Onboarding, Rename, Pagination, Player History & Awards'),
    ]},
]
